name: Build and Package Jar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create Jar File
        run: ./gradlew jar

      - name: Upload Jar Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MyJarArtifact
          path: build/libs/*.jar
